testResponses.getProject = {
  success: {
    status: 200,
    responseText: JSON.stringify(
        {
          "actions":[
            {}
          ],
          "description":"",
          "displayName":"Workstation Chef",
          "name":"Workstation Chef",
          "url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/",
          "buildable":true,
          "builds":[
            {"number":41,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/41/"},
            {"number":40,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/40/"},
            {"number":39,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/39/"},
            {"number":38,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/38/"},
            {"number":37,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/37/"},
            {"number":36,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/36/"},
            {"number":35,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/35/"},
            {"number":34,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/34/"},
            {"number":33,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/33/"},
            {"number":32,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/32/"},
            {"number":31,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/31/"},
            {"number":30,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/30/"},
            {"number":29,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/29/"},
            {"number":28,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/28/"},
            {"number":27,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/27/"},
            {"number":26,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/26/"},
            {"number":25,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/25/"},
            {"number":24,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/24/"},
            {"number":23,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/23/"},
            {"number":22,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/22/"},
            {"number":21,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/21/"},
            {"number":20,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/20/"},
            {"number":19,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/19/"},
            {"number":18,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/18/"},
            {"number":17,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/17/"},
            {"number":16,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/16/"},
            {"number":15,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/15/"},
            {"number":14,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/14/"},
            {"number":13,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/13/"},
            {"number":12,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/12/"},
            {"number":11,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/11/"},
            {"number":10,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/10/"},
            {"number":9,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/9/"},
            {"number":8,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/8/"},
            {"number":7,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/7/"},
            {"number":6,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/6/"},
            {"number":5,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/5/"},
            {"number":4,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/4/"},
            {"number":3,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/3/"},
            {"number":2,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/2/"},
            {"number":1,"url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/1/"}
          ],
          "color":"red",
          "firstBuild":{
            "number":1,
            "url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/1/"
          },
          "healthReport":[
            {
              "description":"Build stability: 2 out of the last 5 builds failed.",
              "iconUrl":"health-40to59.png",
              "score":60
            }
          ],
          "inQueue":false,
          "keepDependencies":false,
          "lastBuild":
          {
            "number":41,
            "url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/41/"
          },
          "lastCompletedBuild":
          {
            "number":41,
            "url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/41/"
          },
          "lastFailedBuild":
          {
            "number":41,
            "url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/41/"
          },
          "lastStableBuild":
          {
            "number":40,
            "url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/40/"
          },
          "lastSuccessfulBuild":
          {
            "number":40,
            "url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/40/"
          },
          "lastUnstableBuild":null,
          "lastUnsuccessfulBuild":
          {
            "number":41,
            "url":"http://collingwood.flood.pivotallabs.com:8080/job/Workstation%20Chef/41/"
          },
          "nextBuildNumber":42,
          "property":[],
          "queueItem":null,
          "concurrentBuild":false,
          "downstreamProjects":[],
          "scm":{},
          "upstreamProjects":[]
        }
    )
  }
};
